---
title: "Справочник к таблицам"
output: 
  word_document:
    reference_docx: word_styles.docx
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F)

```

Ниже таблицы БД для краткости называются **T01**, **T02**, **TRef01**, **TRef02** и т.д., но в базе лучше дать им названия, исходя из содержимого. Столбцы называются так, как в csv-файлах; в базе надо сократить названия, а то запросы будут как предложения у Гоголя.    



# Таблицы-справочники   


## TRef01

Таблица со сведениями об организациях, размещавших контракты. Это справочник по всем организациям-покупателям, строка = организация.      


| № п/п | Файл csv                   | Столбец                      | Тип    | Содержимое                      | Ключ / внешний ключ       |
|:-----:|:---------------------------|:-----------------------------|:-------|:--------------------------------|:--------------------------|
|   1   | `DT_responsibleOrgs_clean` | `responsibleOrg.regNum`      | Строка | номер ответственной организации | кандидат на ключ таблицы, но я бы предпочла ИНН в качестве ID |
|   2   | `DT_responsibleOrgs_clean` | `responsibleOrg.INN`         | Строка | ИНН организации                 | кандидат на ключ таблицы  |
|   3   | `DT_responsibleOrgs_clean` | `responsibleOrg.KPP`         | Строка | КПП организации                 ||
|   4   | `DT_responsibleOrgs_clean` | `responsibleOrg.postAddress` | Строка | почтовый адрес организации; адрес неразобранный, как есть в базе ||
|   5   | в таблицах нет, но каждая папка в данных соответствуте отдельному региону || Строка | наименование региона: по-английски, как они называются на сервере госзакупок (см. файлы README в каждой папке выгрузки) ||
|   6   | `DT_responsibleOrgs_clean` | `lat`                        | Число с плавающей точкой | широта; определяется по адресу ||
|   7   | `DT_responsibleOrgs_clean` | `long`                       | Число с плавающей точкой | долгота; определяется по адресу ||


## TRef02   

Таблица с ограничениями на закупки. Одна строка = уникальное ограничение.        

| № п/п | Файл csv                  | Столбец                   | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:--------------------------|:--------------------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `DT_restrictions_clean`   | `restriction.shortName`   | Строка     | код ограничения на закупку      | ключ (оставляем уникальные)   |
|   2   | `DT_restrictions_clean`   | `restriction.name`        | Строка     | расшифровка ограничения на закупку     ||


## TRef03   

Таблица с двузначными кодами ОКПД2 закупок. Одна строка = уникальный код (строки с пустыми расшифровками можно убрать, эти коды не используются).        

| № п/п | Файл csv                  | Столбец          | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:--------------------------|:-----------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `reference/df_OKPD2_2dig` | `OKPD.2dig`      | Строка     | код товара по ОКПД2, первые 2 символа | ключ |
|   2   | `reference/df_OKPD2_2dig` | `OKPD.2dig.name` | Строка     | расшифровка код товара          ||


## TRef04   

Таблица с полными кодами ОКПД2 закупок. Одна строка = уникальный код.        

| № п/п | Файл csv                  | Столбец          | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:--------------------------|:-----------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `reference/df_all_OKPD2`  | `purchaseObject.OKPD2.code`   | Строка     | код товара по ОКПД2    | ключ |
|   2   | `reference/df_OKPD2_2dig` | `purchaseObject.OKPD2.name`   | Строка     | расшифровка код товара ||


## TRef05   

Коды основания признания торгов несостоявшимися.    

| № п/п | Файл csv                   | Столбец                   | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:---------------------------|:--------------------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `DT_fcsProtocolEF1_clean`  | `abandonedReason.code`    | Строка     | Код основания признания торгов несостоявшимися | Ключ (оставляем уникальные) |
|   2   | `DT_fcsProtocolEF1_clean`  | `abandonedReason.name`    | Строка     | Расшифровка кода | |


## TRef06

Таблица со сведениями об организациях-участниках торгов (исполнители госзаказа). Строка = организация.      


| № п/п | Файл csv                   | Столбец                        | Тип    | Содержимое                       | Ключ / внешний ключ       |
|:-----:|:---------------------------|:-------------------------------|:-------|:---------------------------------|:--------------------------|
|   1   | `DT_fcsProtocolEF3_clean`  | `applications.inn`             | Строка     | ИНН организации-участника    | Ключ (оставляем уникальные) |
|   2   | `DT_fcsProtocolEF3_clean`  | `applications.countryFullName` | Строка     | Страна организации-участника ||
|   3   | `DT_fcsProtocolEF3_clean`  | `applications.countryFullName` | Строка     | Наименование организации-участника ||
|   4   | `DT_fcsProtocolEF3_clean`  | `applications.postAddress`     | Строка     | Адрес организации-участника, как в xml-файле, неразобранный ||
|   5   | `DT_fcsProtocolEF3_clean`  | `lat`      | Число с плавающей точкой | широта; определяется по адресу  ||
|   6   | `DT_fcsProtocolEF3_clean`  | `long`     | Число с плавающей точкой | долгота; определяется по адресу ||


# Таблицы-связи    


## T01   

Таблица по размещённым контрактам (извещениям).    

| № п/п | Файл csv                   | Столбец                   | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:---------------------------|:--------------------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `DT_responsibleOrgs_clean` | `purchaseNumber`          | Строка     | ID закупки                      | Первая часть ключа            |
|   2   | `DT_responsibleOrgs_clean` | `fcsNotificationEF.id`    | Строка     | ID документа из базы госзакупок | попадаются повторяющиеся закупки с одинаковыми номерами и разными датами; причины разные, пока оставляем этот столбец как вторую часть ключа таблицы  |
|   3   | `DT_responsibleOrgs_clean` | `responsibleOrg.INN`      | Строка     | ИНН организации-заказчика       | внешний ключ: `responsibleOrg.INN` из **ТRef01** |
|   4   | `DT_responsibleOrgs_clean` | `docPublishDate`          | Дата+время+часовой пояс | дата размещения извещения       ||
|   5   | `DT_responsibleOrgs_clean` | `lot.maxPrice`            | Число с плавающей точкой | начальная максимальная цена закупки ||
|   6   | `DT_responsibleOrgs_clean` | `lot.currency.code`       | Строка     | код валюты начальной максимальной цены ||


## T02 

Для экономии места можно разбить сведения об извещениях на части. Это часть с ограничениями на закупки.    

| № п/п | Файл csv                | Столбец                   | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:------------------------|:--------------------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `DT_restrictions_clean` | `purchaseNumber`          | Строка     | ID закупки                      | Ключ (выкидываем строки, в которых restriction.shortName == NA)                          |
|   2   | `DT_restrictions_clean` | `fcsNotificationEF.id`    | Строка     | ID документа из базы госзакупок | вторая часть ключа            |
|   3   | `DT_restrictions_clean` | `restriction.shortName`   | Строка     | внешний ключ: `restriction.shortName` из **TRef02** ||


## T03 

Это часть сведений о закупках с кодами товаров по ОКПД2. Там есть таблицы с другими классификаторами (`DT_all_MNNName_clean`, `DT_all_KTRU_clean`), а также объединённый файл со всеми тремя (`DT_TPY_codes_clean`). Их не трогаем, т.к. 'MNNName' (по-русски МНН) это медицинские названия препаратов, а 'KTRU' (по-русски КТРУ) это классификатор специально для госзакупок, построенный на базе ОКПД2.         

| № п/п | Файл csv             | Столбец                     | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:---------------------|:----------------------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `DT_all_OKPD2_clean` | `purchaseNumber`            | Строка     | ID закупки                      | Ключ                          |
|   2   | `DT_all_OKPD2_clean` | `fcsNotificationEF.id`      | Строка     | ID документа из базы госзакупок | вторая часть ключа            |
|   3   | `DT_all_OKPD2_clean` | `purchaseObject.OKPD2.code` | Строка     | полный код ОКПД2 товара закупки | внешний ключ: `purchaseObject.OKPD2.code` из **TRef04**|
|   4   ||| Строка     | оставить первые 2 знака кода ОКПД2       | внешний ключ, `OKPD2.2dig` из **TRef03** |


## T04   

Таблица по результатам первого этапа электронного аукциона.       

| № п/п | Файл csv                  | Столбец                     | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:--------------------------|:----------------------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `DT_fcsProtocolEF1_clean` | `purchaseNumber`            | Строка     | ID закупки                      | Ключ                          |
|   2   | `DT_fcsProtocolEF1_clean` | `fcsProtocolEF1.id`         | Строка     | ID протокола; похоже, что с остальными этапами не связан, но отказываться от столбца нельзя, т.к. есть повторные протоколы для этого же извещения, из которых, по идее, надо брать последний | Ключ, вторая часть |
|   3   | `DT_fcsProtocolEF1_clean` | `protocol01Date`            | Дата+время+часовой пояс | дата и время протокола ||
|   4   | `DT_fcsProtocolEF1_clean` | `application.journalNumber` | Число, целое | номер участника аукциона ||
|   5   | `DT_fcsProtocolEF1_clean` | `admitted`                  | Логическое | принято заявление (TRUE) или нет (FALSE) ||
|   6   | `DT_fcsProtocolEF1_clean` | `abandonedReason.code`      | Строка     | Код основания признания торгов несостоявшимися | внешний ключ: `abandonedReason.code` из **TRef05** |


## T05   

Таблица по результатам второго этапа электронного аукциона.       

| № п/п | Файл csv                  | Столбец                        | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:--------------------------|:-------------------------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `DT_fcsProtocolEF2_clean` | `purchaseNumber`               | Строка     | ID закупки                      | Ключ                          |
|   2   | `DT_fcsProtocolEF2_clean` | `fcsProtocolEF2.id`            | Строка     | ID протокола | Ключ, вторая часть |
|   3   | `DT_fcsProtocolEF2_clean` | `protocol01Date`               | Дата+время+часовой пояс | дата протокола ||
|   4   | `DT_fcsProtocolEF2_clean` | `application.journalNumber`    | Число, целое | номер участника аукциона ||
|   5   | `DT_fcsProtocolEF2_clean` | `application.firstOffer.price` | Число с плавающей точкой | первое ценовое предложение участника аукциона ||
|   6   | `DT_fcsProtocolEF2_clean` | `application.firstOffer.date`  | Дата+время+часовой пояс  | дата-время первого ценового предложения участника ||
|   7   | `DT_fcsProtocolEF2_clean` | `application.lastOffer.price`  | Число с плавающей точкой | последнее ценовое предложение участника аукциона ||
|   8   | `DT_fcsProtocolEF2_clean` | `application.lastOffer.date`   | Дата+время+часовой пояс  | дата-время последнего ценового предложения участника ||
|   9   | `DT_fcsProtocolEF2_clean` | `application.priceOffers.offersQuantity` | Число, целое | количество ценовых предложений участника ||


## T06   

Таблица по результатам третьего этапа электронного аукциона.       

| № п/п | Файл csv                  | Столбец                        | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:--------------------------|:-------------------------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `DT_fcsProtocolEF2_clean` | `purchaseNumber`               | Строка     | ID закупки                      | Ключ                          |
|   2   | `DT_fcsProtocolEF2_clean` | `fcsProtocolEF2.id`            | Строка     | ID протокола | Ключ, вторая часть |
|   3   | `DT_fcsProtocolEF2_clean` | `protocol01Date`               | Дата+время+часовой пояс | дата протокола ||
|   4   | `DT_fcsProtocolEF2_clean` | `applications.inn`             | Строка | ИНН участника аукциона | внешний ключ: `applications.inn` из **TRef06** |
|   5   | `DT_fcsProtocolEF2_clean` | `application.journalNumber`    | Число, целое | номер участника аукциона ||
|   6   | `DT_fcsProtocolEF2_clean` | `application.firstOffer.price` | Число с плавающей точкой | первое ценовое предложение участника аукциона ||
|   8   | `DT_fcsProtocolEF2_clean` | `application.firstOffer.date`  | Дата+время+часовой пояс  | дата-время первого ценового предложения участника ||
|   9   | `DT_fcsProtocolEF2_clean` | `application.lastOffer.price`  | Число с плавающей точкой | последнее ценовое предложение участника аукциона ||
|  10   | `DT_fcsProtocolEF2_clean` | `application.lastOffer.date`   | Дата+время+часовой пояс  | дата-время последнего ценового предложения участника ||
|  11   | `DT_fcsProtocolEF2_clean` | `application.priceOffers.offersQuantity` | Число, целое | количество ценовых предложений участника ||
|  12   | `DT_fcsProtocolEF2_clean` | `application.appRating.drop.reason` | Строка | Причина отклонения заявки; там смесь текстовых причин и логических значений, типичный хаос ||


## T07   

Таблица по результатам электронного аукциона.       

| № п/п | Файл csv                      | Столбец            | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:------------------------------|:-------------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `DT_fcsPlacementResult_clean` | `purchaseNumber`   | Строка     | ID закупки | Ключ                          |
|   2   | `DT_fcsPlacementResult_clean` | `procedurelFailed` | Логическое | TRUE если процедура не состоялась ||
|   3   | `DT_fcsPlacementResult_clean` | `application.journalNumber` | Число, целое | номер участника-победителя, но... (см. след. столбец) ||
|   4   | `DT_fcsPlacementResult_clean` | `application.appRating`     | Число, целое | место победителя; есть значения 1 и 0, тадам! есть ещё NA у несостоявшихся аукционов ||
|   5   | `DT_fcsPlacementResult_clean` | `application.result` | Строка | Буквенный код статуса победителя; надо сделать справочник и привязать к нему ||
|   6   | `DT_fcsPlacementResult_clean` | `application.price`  | Число с плавающей точкой | Окончательная цена по результатам аукциона ||



## T08   

Таблица с отменёнными аукционами.       

| № п/п | Файл csv                      | Столбец            | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:------------------------------|:-------------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `DT_fcsProtocolCancel_clean`  | `purchaseNumber`   | Строка     | ID закупки | Ключ                          |
|   2   | `DT_fcsProtocolCancel_clean`  | `fcsProtocolCancel.docDate`   | Дата+время+часовой пояс     | Дата отмены ||



## T09   

Таблица по аукционам, на которые подана только одна заявка.    

| № п/п | Файл csv                          | Столбец            | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:----------------------------------|:-------------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `DT_fcsProtocolEFSingleApp_clean` | `purchaseNumber`   | Строка     | ID закупки | Ключ                          |
|   2   | `DT_fcsProtocolEFSingleApp_clean` | `protocolSingleAppDate`   | Дата+время+часовой пояс     | Дата протокола ||
|   3   | `DT_fcsProtocolEFSingleApp_clean` | `application.inn`   | Строка     | ИНН участника | внешний ключ: `application.inn` из **TRef06** |
|   4   | `DT_fcsProtocolEFSingleApp_clean` | `proc.success`   | Логическое | TRUE, если процедура состоялась успешно ||
|   5   | `DT_fcsProtocolEFSingleApp_clean` | `winnerPrice`    | Число с плавающей точкой | итоговая цена закупки ||
|   6   | `DT_fcsProtocolEFSingleApp_clean` |  на основе столбцов  | Число с плавающей точкой | итоговая цена закупки ||


## T10   

Таблица по причинам отказов на аукционах, на которые подана только одна заявка (1 этап аукциона).    

| № п/п | Файл csv                          | Столбец            | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:----------------------------------|:-------------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `DT_fcsProtocolEFSingleApp_clean` | `purchaseNumber`   | Строка     | ID закупки | Ключ                          |
|   2   | `DT_fcsProtocolEFSingleApp_clean` | на основе трёхлогических: `rejected.ANR`, `rejected.DNFV`, `rejected.PNRD`; после точки стоит код причины отказа, берём те строки, где в этих столбцах 1 | Строка     | код причины отказа участнику | внешний ключ: надо сделать справочник на основе `reference/Все+справочники+по+ЭП_v42+(10.3)+(Добавлен+ЭОК).xslx` |


## T10   

Таблица по причинам отказов на аукционах, в которых принял участие только один поставщик (2 этап аукциона).    

| № п/п | Файл csv                          | Столбец            | Тип        | Содержимое                      | Ключ / внешний ключ           |
|:-----:|:----------------------------------|:-------------------|:-----------|:--------------------------------|:------------------------------|
|   1   | `DT_fcsProtocolEFSingleApp_clean` | `purchaseNumber`   | Строка     | ID закупки | Ключ                          |
